apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cluster
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-cluster
    spec:
      containers:
        - name: java-app
          image: 540179555644.dkr.ecr.ap-south-1.amazonaws.com/pipeline3:17
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java-web-app
