apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-login-app
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: java-login-app
    spec:
      containers:
        - name: pipeline3
          image: 307815379384.dkr.ecr.us-east-1.amazonaws.com/pipeline3:1
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: java-login-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java-web-app
